### PR TITLE
std::error::Error support

### LINKED ISSUE #273: Logging std::error::Error
Currently, it's not specified how to log an error type implementing the `Error` trait. The naive implementation would use `%`, but that's not entirely right as the information about source is lost (`Display` is not supposed to write it).

One could write a helper method to iterate over sources and write them separated with `: `. This works but the structural information is lost. I believe that error types are something one would very much desire to log (at least that's what I do), so it'd be nice to provide a better support for it.

I propose to add a new method to the `Serializer` called `emit_error()` that will accept any type implementing `std::error::Error` and by default iterates through sources and writes them separated by `: `.

I also propose adding a new modifier, e.g `#` for the macros that will log an error using this method.

### PR DESCRIPTION
**Pull request by Kixunil**
Explicit support for `std::error::Error`

This change implements support for `std::error::Error`, which is a
popular trait used for errors. Since people usually log errors, it makes
sense to support them directly.

Changes include:

* Adding `emit_error()` method to `Serializer`
* Adding a default implementation for `emit_error()`
* Adding a helper wrapper struct for serializing foreign types that
  don't impl `slog::Value` but do impl `std::error::Error`
* Adding `#` prefix to macro, so that the wrapper can be instantiated
  easily
* Adding `impl Value for std::io::Error`
* Adding tests

Closes #273

Make sure to:

* [x] Add an entry to CHANGELOG.md (if neccessary)

This is a preview and the compatibility of `#` was not deeply inspected yet. I'm going to do it soon, just wanted to show my changes soon.

This also contains a commit fixing compilation of `no_std` tests.

### CODE REVIEW

File: src/tests.rs [hunk 1]
```diff
@@ -205,6 +291,7 @@ fn expressions_fmt() {
     info!(log, "message"; "f" => %f, "d" => ?d);
 }
 
+#[cfg(feature = "std")]
```
Comment (dpc) [inline src/tests.rs:294]: Why is that needed?

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
Let's let it sit for a moment in git, and please remind me to release it at some point. Thanks!

File: src/tests.rs (hunk 1 above)
Comment (Kixunil) [reply src/tests.rs:294]: There were unrelated test failures (that's why I created two separate commits)

**Comment by Kixunil** [comment]
Thank you too!

**Comment by davepacheco** [comment]
Thanks for doing this!

I'm trying to figure out how to use this.  (Sorry if I missed some examples or docs but I didn't find much.)  I'm looking for the best way to log an error that impls std::error::Error.  If I'm reading this right, one ought to be able to do something like:

```
info!(log, "message"; "error" => # error)
```

where `error` impls std::error::Error.  Is that right?  But this takes ownership of the error -- I can't then propagate it to the caller.  If I try to use `#&error`, the error doesn't live long enough.  (Does the logger hold onto the borrowed value?)

I think I expected that I could pass a reference (so that I can still use the error) and slog would copy and/or serialize whatever it needed for the log.  Am I missing something?

**Comment by dpc** [comment]
https://github.com/slog-rs/slog/pull/274/files#diff-a0262fea108af44a98cc49e5eb72641963dd816513f2d0a22eb738fcfed55ebeR142 this example seems to work. is it of any help? Can you paste full compiler message and code excerpt it it does not?

**Comment by davepacheco** [comment]
Thanks!  That is helpful.  But that example passes the owned error to the logger.  Is there any way to log the error and maintain ownership so I can return it to the caller too?

**Comment by dpc** [comment]
Hmmm... https://github.com/slog-rs/slog/blob/f9e30f0dd9bad610227d9374001fcc13d5b7c8c8/src/lib.rs#L423

I think this is a shortcomming of https://github.com/slog-rs/slog/blob/f9e30f0dd9bad610227d9374001fcc13d5b7c8c8/src/lib.rs#L3168 which wants `E` by value or something.

If you have time, you could trying toying with it and submit a PR. We can either support `#&` in a macro, or make `ErrorValue` work with `Error` or `&Error` somehow.

**Comment by davepacheco** [comment]
Thanks.

**Comment by Kixunil** [comment]
I believe this is a limitation of `std::error::Error` trait but maybe I made a mistake when I implemented it. I don't remember exact details now.

**Comment by dpc** [comment]
We migh require `Clone + Send` if we are to take a reference.

**Comment by davepacheco** [comment]
Sorry in advance if this is an ignorant question, as I haven't spent much time in the slog source before.  What if we instead iterate the source chain and store the messages along the way?  And then not need to clone the Error or pass it between threads?

**Comment by dpc** [comment]
I guess we want to let the `Serializer` decide how to serialize the error, so we want to pass it all the way there undisturbed.

**Comment by Kixunil** [comment]
@davepacheco storing messages as `String` loses information which is already used in one crate and storing this sources is impossible because of lifetime issues. 

If your error can be cloned why not just do that? If it can't, maybe it can be converted to another error?

One pattern I used to deal with this problem was in HTTP server, where I had a function that converted the error to a simpler version and logged, then another function converted it to response. The general idea was something like this:

```rust
fn log_and_convert(logger: Logger, error: MyError) -> ResponseError {
    let response_error = match error {
        MyError::SqlError(_) => ResponseError::Internal,
        MyError::Io(error) if error.kind() == io::ErrorKind::NotFound => ResponseError::NotFound,
        // ...
    };

     error!(logger, "Request failed"; "error" => #error);

     response_error
}
```

**Comment by davepacheco** [comment]
To give more context about what I'm trying to do:  I've got a few different applications and several different library crates.  I'm looking to standardize on a pattern to allow any of these crates to log errors (or other messages) to a caller-provided logger.  In this case, each crate would be logging its own error types and maybe those of dependent crates, too.  (I expected this would be a common use case.  Maybe it's not?)

I don't want to require these to be `Clone` because a lot of important errors do not impl `Clone`.  The first one I ran into was `anyhow::Error`, which is pretty popular. Its author [explains that it doesn't impl Clone because so many other important errors don't impl `Clone`](https://github.com/dtolnay/anyhow/issues/7#issuecomment-539383249).

@Kixunil In your example, I infer that the HTTP server only logs an error in one spot and it doesn't care about preserving the original error for the caller.  Your suggestion makes sense there.  In my case, it seems like a lot of work to have each crate define an additional internal error type just for logging, plus a conversion from the actual error to that type, and then use the conversion in all the places where an error might be logged.

Now, I can commonize a bunch of that.  Since I'm only looking to log information that's common to any `std::error::Error`, I could define _one_ struct used by all these crates, plus a conversion from `&std::error::Error` to my custom struct.  I imagine the struct would store either the concatenated messages as I suggested, or a `Vec<String>` for the messages, or a similar structure to include the formatted backtraces (if wanted).  This struct doesn't even need to `impl std::error::Error` itself -- it could be something whose `Display` or `Debug` impl produces whatever's wanted in the log.  This would be an improvement, though users would still need to explicitly perform the conversion in all the places that log an error.

I just expected this is what `slog::ErrorValue` was.  It has the advantage that the `#` syntax is a concise way to request the conversion.  Anyway, I think I can do this on my own without support in `slog` using a bit more boilerplate at each macro invocation.

Thanks everyone for the help and suggestions.  If something about this goal or approach seems like a bad idea, I'd love to hear more about why or if there are other patterns that people use for this!

**Comment by Kixunil** [comment]
You might want to look at `log` crate which explores key-value records as well, maybe you can find some inspiration there.

If you can't consume the error type, then what you suggest makes sense although I'm not convinced logging an error and then passing it to the caller is better than just letting the caller log the error.
